import { Inter } from 'next/font/google'
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Web Tutorial',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const resp = await fetch('http://localhost:9999/topics');
  const topics = await resp.json();

  return (
    <html >
      <body >
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map( (topic) => 
            {return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li> })}
        </ol>
        {children}
        <ul>
          <li><a  href = "/create">Create</a></li>
          <li><a  href = "/udpate/1">Update</a></li>
          <li><input type="button" value="delete"/></li>
        </ul>
      </body>
    </html>
  )
}
