import { Inter } from 'next/font/google'
import Link from 'next/link';
import './globals.css';
import { Control } from './Control';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Web Tutorial',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});  // 글목록을 가지고 와서 캐시를 안 쓰겠다.. 고 세팅하는 것임. 
  const topics = await resp.json();

  return (
    <html >
      <body >
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map( (topic) => 
            {return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li> })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
